### ISSUE TITLE
[Bug]: Push notifications rejected by eu.prod.push.monal-im.org

### ISSUE THREAD

**Issue by devops-42** [monal-im/Monal#1064]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

17.5

### macOS system version (if applicable)

13.6.7

### Monal version

6.3.1

### Used XMPP server (domain)

custom

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

24.02

### How many accounts are you using in Monal?

1

### What happened?

Hi,

I played around with ejabberd and Monal and succeeded to setup a local server where Monal is able to connect to via TLS (port 5223). The certificate is generated using Let's Encrypt. My listen config looks like:

```
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls_required: true
    protocol_options: 'TLS_OPTIONS'
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s

  -
    port: 5223
    ip: "::"
    module: ejabberd_c2s
    starttls_required: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
```

When sending message which would require push, the ejabber service issues the following error message:
```
eu.prod.push.monal-im.org rejected notification for *****@mysuper.fancy-doma.in temporarily: Stream closed by local host: STARTTLS is disabled in local configuration (unsupported-feature) (remote-server-timeout)
```

Double-checked, that the required according to FAQ modules are configured:
```
modules:  
    mod_client_state: {}
    mod_stream_mgmt: {}
    mod_push: {}
    mod_push_keepalive: {}
    mod_mam: {}
```

Am I missing sth in the configuration?

Thanks a lot for any help!

Cheers ✌️

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications
