### ISSUE TITLE
[Bug]: stun/turn credential problems

### ISSUE THREAD

**Issue by volga629-1** [monal-im/Monal#1104]
### What Monal Release channel are you using?

AppStore

### iOS system version (if applicable)

17.5.1

### macOS system version (if applicable)

17.5.1

### Monal version

6.4

### Used XMPP server (domain)

networklab.ca

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

24.06

### How many accounts are you using in Monal?

>= 6

### What happened?

For video audio calls ejabberd stun , turn after discovery is failing. Based on ejabberd logs authentication sent incorrectly and result call is failing. 

### Anything else?

I will submit logs soon

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
Please show us the following:

- `ejabberd_stun`-Listener
- `mod_stun_disco`-Config
- The actual loglines showing the error you mentioned (you can strip off ip addresses etc.)

**Comment by volga629-1** [comment]
Here are information 

```
  -
    port: 3478
    transport: udp
    module: ejabberd_stun
    auth_realm: user
    auth_type: user
    use_turn: true
    turn_min_port: 51000
    turn_max_port: 54000
    turn_ipv4_address: pubic ip

  -
    port: 5349
    transport: tcp
    module: ejabberd_stun
    auth_realm: user
    auth_type: user
    tls: true
    use_turn: true
    turn_min_port: 51000
    turn_max_port: 54000
    ip: 10.18.130.29
    turn_ipv4_address: public IP 


  mod_stun_disco:
    access: local
    offer_local_services: true
    credentials_lifetime: 4
    secret: 
    services:
      -
       host: disco.domain.com
       port: 3478
       type: stun
       transport: udp
       restricted: false
      -
       host: disco.domain.com
       port: 3478
       type: turn
       transport: udp
       restricted: true
      -
       host: disco.domain.com
       port: 5349
       type: turns
       transport: tcp
       restricted: true
```

Log

```

2024-07-08 14:15:29.758738-04:00 [info] <0.622.0>@mod_stun_disco:handle_call/3:332 Offering STUN/TURN services to user@domain.com/Monal-iOS.80f7d04b (cad8c3515d7e15f0)
2024-07-08 14:15:32.098645-04:00 [notice] <0.469.0>@stun:process/2:248 Failed long-term STUN/TURN authentication [UDP, session 86o7uy6bxfr7, user 1720462502:6d25cc055d7e15f0, client 129.222.194.45:34013]
2024-07-08 14:15:32.104233-04:00 [notice] <0.469.0>@stun:process/2:248 Failed long-term STUN/TURN authentication [UDP, session u11tt9xpu32o, user 1720462502:6d25cc055d7e15f0, client 129.222.194.45:13814]
2024-07-08 14:15:32.115034-04:00 [notice] <0.469.0>@stun:process/2:248 Failed long-term STUN/TURN authentication [UDP, session bqmh1pbbzk6v, user 1720462502:6d25cc055d7e15f0, client 129.222.194.45:43799]
2024-07-08 14:15:32.115194-04:00 [notice] <0.469.0>@stun:process/2:248 Failed long-term STUN/TURN authentication [UDP, session efcesl0tl7xu, user 1720462502:6d25cc055d7e15f0, client 129.222.194.45:37016]
```

**Comment by weiss** [comment]
> `credentials_lifetime: 4`

Here you're telling ejabberd to invalidate the temporary TURN credentials 4 seconds after handing them out to the client.  That's the culprit I guess.

I'd suggest sticking to the [example configuration][1]:

```yaml
listen:
  -
    port: 3478
    ip: "::"
    transport: udp
    module: ejabberd_stun
    use_turn: true
    ## The server's public IPv4 address:
    # turn_ipv4_address: "203.0.113.3"

modules:
  mod_stun_disco: {}
```

The `mod_stun_disco` options you're using are basically just needed to configure _external_ TURN servers.  And offering TLS will usually just add negotiation latency without serving an actual purpose, as clients will prefer UDP (to avoid additional A/V stream latency) and WebRTC streams are [end-to-end encrypted][2] anyway.  (The only real use case is offering TURNS on port 443 for circumventing restrictive firewalls.)

[1]: https://raw.githubusercontent.com/processone/ejabberd/master/ejabberd.yml.example
[2]: https://webrtc-security.github.io
